# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Check dist/

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm ci

    - name: Rebuild the dist/ directory
      run: npm run build

    - name: Compare the expected and actual dist/ directories
      id: diff
      run: git diff --exit-code -- dist/

    # If index.js was different than expected, upload the expected version as an artifact
    - uses: actions/upload-artifact@v2
      if: ${{ failure() && steps.diff.conclusion == 'failure' }}
      with:
        name: dist
        path: dist/
